# Generated by Django 3.0.6 on 2020-05-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableschedule',
            name='time_schedule',
        ),
        migrations.AddField(
            model_name='classroom',
            name='auditorium_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=8, help_text='Имя направления', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.TimeField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='half_lesson',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='schedule.HalfLesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='table_schedule',
            field=models.ManyToManyField(to='schedule.TableSchedule'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Имя кафедры', max_length=100),
        ),
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
