# Generated by Django 3.0.6 on 2020-05-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200531_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='type_subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота')], max_length=11),
        ),
        migrations.DeleteModel(
            name='DayOfTheWeek',
        ),
        migrations.DeleteModel(
            name='TypeClassroom',
        ),
        migrations.DeleteModel(
            name='TypeSubject',
        ),
    ]
