# Generated by Django 3.0.6 on 2020-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200531_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная'), ('', 'Без типа')], max_length=12),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('1 нед', '1 неделя'), ('2 нед', '2 неделя'), ('', 'Еженедельно')], max_length=11),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная'), ('', 'Без типа')], max_length=12),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.AddField(
            model_name='schedule',
            name='specific_date',
            field=models.ManyToManyField(to='schedule.SpecificDate'),
        ),
    ]
