# Generated by Django 3.0.6 on 2020-05-31 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200531_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdiscipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='halflesson',
            options={'verbose_name': 'Промежуток полупары', 'verbose_name_plural': 'Промежутки полупар'},
        ),
        migrations.AlterModelOptions(
            name='provision',
            options={'verbose_name': 'Софт(оборудование)', 'verbose_name_plural': 'Софт(оборудование)'},
        ),
        migrations.AlterModelOptions(
            name='restday',
            options={'verbose_name': 'Выходной день', 'verbose_name_plural': 'Выходные дни'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='specificdate',
            options={'verbose_name': 'Спец дата занятия', 'verbose_name_plural': 'Спец даты занятий'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='tableschedule',
            options={'verbose_name': 'Общее расписание', 'verbose_name_plural': 'Общее расписание'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'Рабочее время преподавателя', 'verbose_name_plural': 'Рабочее время преподавателя'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='classroom',
            name='housing',
            field=models.CharField(choices=[('Тушино', 'Тушино'), ('Миуссы', 'Миуссы')], default=1, max_length=12, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicdiscipline',
            name='course',
            field=models.ManyToManyField(to='schedule.Course', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='academicdiscipline',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='auditorium_number',
            field=models.CharField(max_length=50, verbose_name='Номер аудитории'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='provision',
            field=models.ManyToManyField(to='schedule.Provision', verbose_name='Софт(оборудование)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная'), ('', 'Без типа')], max_length=12, verbose_name='Тип аудитории'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='number_of_hours',
            field=models.IntegerField(verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.AcademicDiscipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(verbose_name='День экзамена'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Course', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='the_size_of_the_group',
            field=models.IntegerField(verbose_name='Численность группы'),
        ),
        migrations.AlterField(
            model_name='halflesson',
            name='time_end',
            field=models.TimeField(verbose_name='Окончание промедутка'),
        ),
        migrations.AlterField(
            model_name='halflesson',
            name='time_start',
            field=models.TimeField(verbose_name='Начало промедутка'),
        ),
        migrations.AlterField(
            model_name='provision',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название софта(оборудования)'),
        ),
        migrations.AlterField(
            model_name='restday',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название выходного'),
        ),
        migrations.AlterField(
            model_name='restday',
            name='rest_day',
            field=models.DateField(verbose_name='Дата выходного'),
        ),
        migrations.AlterField(
            model_name='restday',
            name='table_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.TableSchedule', verbose_name='Общее расписание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота')], max_length=12, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('1 нед', '1 неделя'), ('2 нед', '2 неделя'), ('', 'Еженедельно')], max_length=12, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='half_lesson',
            field=models.ManyToManyField(to='schedule.HalfLesson', verbose_name='Промежуток полупары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specific_date',
            field=models.ManyToManyField(to='schedule.SpecificDate', verbose_name='Спец даты занятий'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='table_schedule',
            field=models.ManyToManyField(to='schedule.TableSchedule', verbose_name='Общее расписание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher', verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='specificdate',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='academic_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.AcademicDiscipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('л', 'Лекция'), ('с', 'Семинар'), ('лаб', 'Лабараторная'), ('', 'Без типа')], max_length=12, verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='tableschedule',
            name='mod_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tableschedule',
            name='semester',
            field=models.IntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_the_week',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота')], max_length=12, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='number_of_working_hours',
            field=models.TimeField(default='08:00:00', verbose_name='Количество рабочих часов'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher', verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='the_daily_starting_time',
            field=models.TimeField(default='09:00:00', verbose_name='Начало рабочего дня'),
        ),
    ]
